activateUser=user1
walletAmount=21500
rule.names=rule2,rule3,rule10,rule14,rule8,rule13,rule12,rule9

# Rule Names from premium-rules.drl
rule1=Repeated Lenders - Low Risk
rule2=Repeated Lenders - Medium Risk
rule3=Repeated Lenders - High Risk
rule4=Trusted Lenders - Low Risk
rule5=Trusted Lenders - Medium Risk
rule6=Trusted Lenders - High Risk
rule7=Good Lenders
rule8=Normal Lenders
rule9=Bulk Lenders
rule10=Repeated Business Lenders
rule11=Good Business Lenders
rule12=Bulk Business Lenders
rule13=Filling Fast Lenders
rule14=Daily Repayment Lenders
rule15=Monthly Repayment - High Risk

## No need to modify below
user1.mobileNumber=7008565316
user1.user=saraswati
user1.email.username=abika.2009@gmail.com
user1.email.password=${SARASWATI_EMAIL_PASSWORD}

user2.mobileNumber=9090978607
user2.user=abikananda
user2.email.username=abikananda.2012@gmail.com
user2.email.password=${ABIKANANDA_EMAIL_PASSWORD}

# No need to change as it dynamically set in the code when running repeated lender rules
businessFilter=false
# No need to change as it dynamically set in the code when running repeated lender rules
repeatedLoan=false
# No need to change as it dynamically set in the code when running repeated lender rules
low_high_risk_filter=false

db.url=jdbc:mysql://localhost:3306/pfmp?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Kolkata
db.username=root
db.password=${DB_PASSWORD}
